name: rfp-service
version: '0.0.5.2'
synopsis: RFPService service
description: RFPService Service
category: Web
author: RFP <doddi@kott.is>
maintainer: RFP <doddi@kott.is>
copyright: 2020 RFP
license: MIT
git: https://www.gitlab.com/reiknirit/rfp-service
dependencies:
- base >=4.9 && <5.0
- persistent ==2.9.2
- persistent-template ==2.6.0
- persistent-postgresql
- dotenv
- wai-extra
- wai-cors
- mtl
- hslogger
- fast-logger
- http-types
- text
- time
- hworker
- hedis
- optparse-applicative
library:
  source-dirs: src
  ghc-options: -fwarn-unused-imports
  exposed-modules:
  - Config
  - Models
  - API
  - API.Service
  - API.Attachment
  - API.Submission
  - API.User
  - Cli
  - Elasticsearch
  - Utils
  - Logger
  - Worker.Base
  - Worker.RFPWorker
  dependencies:
  - aeson
  - bloodhound
  - bytestring
  - http-client
  - http-types
  - monad-control
  - monad-logger
  - servant
  - servant-multipart
  - servant-server
  - transformers
  - wai
  - warp
  - text
  - containers
  - fast-logger
  - unordered-containers
  - safe
  - uuid
  - hip
  - filepath
  - parser-combinators
  - directory
  - bcrypt
  - sendgrid-v3
executables:
  rfp-service:
    main: app/Main.hs
    ghc-options: -fwarn-unused-imports
    dependencies:
    - rfp-service
    - base >=4.9 && <5.0
    - wai
    - warp
    - monad-logger
    - utf8-string
    - bytestring
    - base64-bytestring
  rfp-worker:
    main: app/Worker.hs
    ghc-options: -fwarn-unused-imports
    dependencies:
    - rfp-service
